apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    project: {{ .Values.project }}
    role: {{ .Values.type }}
    env: {{ .Values.env }}
spec:
  type: {{ .Values.servicetype }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
    project: {{ .Values.project }}
    role: {{ .Values.type }}
    env: {{ .Values.env }}
